### ISSUE TITLE
ValueError: cannot infer dimensions from zero sized index arrays

### ISSUE THREAD

**Issue by ArnimJenett** [jni/skan#90]
Hi Juan, when feeding 3D skeletons (generated with skimage) into skan we are getting the error cited in the headline (I posted the entire Traceback below) 
To me/us it looks like it is complaining about the parameter 'spacing', which we tried in all shapes and forms (int, float, array, none) with no progress. 
The 3D array (of the skelton) is well-formed and the call looks like this:
```Python
import numpy as np
import skimage.io as io
from skan import Skeleton, summarize
import pandas as pd
```
/snip/
```Python
            subvol=np.asarray(vallist).reshape(istep,jstep,kstep) # reshape list to array of desired dimensions
\# feed subvolume to skeleton analysis            
            branch_data = summarize(Skeleton(subvol, spacing=1))
# write results to file
            branch_data.to_csv(dir+'skan'+str(div)+'.csv') # dummy output, overwriting file 
```
Could you please advise, how we can get this going? Is this an issue in the code or are we missing the point somewhere?
cheers, aRnim

```Python---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-894a5708f4f3> in <module>
     44 #            print(subvol,"\n")
     45 # feed subvolume to skeleton analysis
---> 46             branch_data = summarize(Skeleton(subvol, spacing=1))
     47 # write results to file
     48             branch_data.to_csv(dir+'skan'+str(div)+'.csv') # dummy output, overwriting file

~\Anaconda3\envs\AY-312-DR-36\lib\site-packages\skan\csr.py in __init__(self, skeleton_image, spacing, source_image, _buffer_size_offset, keep_images)
    314                  _buffer_size_offset=None, keep_images=True):
    315         graph, coords, degrees = skeleton_to_csgraph(skeleton_image, 
--> 316                                                                spacing=spacing)
    317         if np.issubdtype(skeleton_image.dtype, np.float_):
    318             pixel_values = ndi.map_coordinates(skeleton_image, coords.T,

~\Anaconda3\envs\AY-312-DR-36\lib\site-packages\skan\csr.py in skeleton_to_csgraph(skel, spacing, value_is_height, unique_junctions)
    622     steps, distances = raveled_steps_to_neighbors(skelint.shape, ndim,
    623                                                   spacing=spacing)
--> 624     graph = _pixel_graph(skelint, steps, distances, num_edges, height)
    625 
    626     if unique_junctions:

~\Anaconda3\envs\AY-312-DR-36\lib\site-packages\skan\csr.py in _pixel_graph(image, steps, distances, num_edges, height)
     57         k = _write_pixel_graph_height(image, height, steps, distances,
     58                                       row, col, data)
---> 59     graph = sparse.coo_matrix((data[:k], (row[:k], col[:k]))).tocsr()
     60     return graph
     61 

~\Anaconda3\envs\AY-312-DR-36\lib\site-packages\scipy\sparse\coo.py in __init__(self, arg1, shape, dtype, copy)
    144                 if shape is None:
    145                     if len(row) == 0 or len(col) == 0:
--> 146                         raise ValueError('cannot infer dimensions from zero '
    147                                          'sized index arrays')
    148                     M = operator.index(np.max(row)) + 1

ValueError: cannot infer dimensions from zero sized index arrays`
```

**Comment by jni** [comment]
@ArnimJenett a blast from the past!!! Hello!!! :wave: :wave: :wave: 

If you look at the last two bits from the traceback:

```pytb
~\Anaconda3\envs\AY-312-DR-36\lib\site-packages\skan\csr.py in _pixel_graph(image, steps, distances, num_edges, height)
     57         k = _write_pixel_graph_height(image, height, steps, distances,
     58                                       row, col, data)
---> 59     graph = sparse.coo_matrix((data[:k], (row[:k], col[:k]))).tocsr()
     60     return graph
     61 

~\Anaconda3\envs\AY-312-DR-36\lib\site-packages\scipy\sparse\coo.py in __init__(self, arg1, shape, dtype, copy)
    144                 if shape is None:
    145                     if len(row) == 0 or len(col) == 0:
--> 146                         raise ValueError('cannot infer dimensions from zero '
    147                                          'sized index arrays')
    148                     M = operator.index(np.max(row)) + 1
```

it looks like the row and column arrays are size 0. The only way this can happen, I think, is if the image has zero foreground pixels. Is this possible? If you can reproduce the error with a sample image that you can share, that will be super useful to help me figure out what is going on.

In terms of fixes, a workaround is to fix your data =P, but skan should certainly do better, and return an empty table if needed.

Or maybe there's an actual bug and your image isn't empty. If you can provide some example data + complete script, I can try to figure this out!

**Comment by ArnimJenett** [comment]
@jni yes, it's fun to see how the scientific family is spreading around the world. ;)
Thank you very much for pointing us in the right direction.
As we are processing sub-volumes of bigger main-volume it is indeed possible that a sub-volume contains zero foreground pixels (as in not a single branch within that sub-volume). 
To solve this problem we simply integrated a check against empty arrays (no foreground pixels) before the call
```Python
...
            subvol=np.asarray(vallist).reshape(istep,jstep,kstep) # reshape list to array of desired dimensions
            subvolmax=np.amax(subvol)
            if (subvolmax > 0):
# feed subvolume to skeleton analysis            
                branch_data = summarize(Skeleton(subvol, spacing=1))           
            else:
                branch_data = pd.DataFrame(reader("0")) # 'empty table' (dummy)
# write results to file 
            branch_data.to_csv(dir+'skan'+str(div)+'.csv') # dummy output, overwriting file 
```
This is running, however it gets stuck after some time with a new error message (Traceback below)
We tested the sub-stack-iterator independently - that runs through.
The example main-volume.shape is `(400, 1600, 800)` and the error happens at the coordinates '20 800 440' , meaning nicely within the main-volume. 
I therefore do not understand how we can overun an index. 
Would you mind to help us out, again? 
cheers, arnim

```Python
(400, 1600, 800)
steps: 20 80 40
li: 0 0 0 : 0
0000-0000-0000
/snip/
0020-0800-0400
li: 20 800 440 : 0

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-21-4919670146ce> in <module>
     55 #                print("svm:",subvolmax)
     56 # feed subvolume to skeleton analysis
---> 57                 branch_data = summarize(Skeleton(subvol, spacing=1))
     58 #                branch_data.to_csv(dir+'skan'+str(div)+'.csv') # dummy output, overwriting file
     59             else:

~\Anaconda3\envs\AY-312-DR-36\lib\site-packages\skan\csr.py in __init__(self, skeleton_image, spacing, source_image, _buffer_size_offset, keep_images)
    324         self.coordinates = coords
    325         self.paths = _build_skeleton_path_graph(self.nbgraph,
--> 326                                     _buffer_size_offset=_buffer_size_offset)
    327         self.n_paths = self.paths.shape[0]
    328         self.distances = np.empty(self.n_paths, dtype=float)

~\Anaconda3\envs\AY-312-DR-36\lib\site-packages\skan\csr.py in _build_skeleton_path_graph(graph, _buffer_size_offset)
    247                         visited, degrees)
    248     paths = sparse.csr_matrix((path_data[:n], path_indices[:n],
--> 249                                path_indptr[:m]), shape=(m-1, n))
    250     return paths
    251 

~\Anaconda3\envs\AY-312-DR-36\lib\site-packages\scipy\sparse\compressed.py in __init__(self, arg1, shape, dtype, copy)
    103             self.data = self.data.astype(dtype, copy=False)
    104 
--> 105         self.check_format(full_check=False)
    106 
    107     def getnnz(self, axis=None):

~\Anaconda3\envs\AY-312-DR-36\lib\site-packages\scipy\sparse\compressed.py in check_format(self, full_check)
    175             raise ValueError("indices and data should have the same size")
    176         if (self.indptr[-1] > len(self.indices)):
--> 177             raise ValueError("Last value of index pointer should be less than "
    178                              "the size of index and data arrays")
    179 

ValueError: Last value of index pointer should be less than the size of index and data arrays
```

**Comment by jni** [comment]
Hello again! That looks more serious/trickier!

Are you familiar with pdb or other debuggers? What I would do here is `python -m pdb my_script.py`. Then when it crashes you can move around in the stack trace and figure out what went wrong. Most IDEs (Spyder, VSCode, PyCharm) also have built in debuggers.

I'm totally happy to do this for you, but I'll need some test data! Since you are processing sub-chunks, maybe you can get this to fail on only the specific failing chunk, and share that chunk with me?

By the way, why are you chunking the volumes? By my calculation your full volume is just 512MB, which I would hope skan could handle relatively easily...!

**Comment by ArnimJenett** [comment]
### Minimal skeleton size required?
while 'fixing my data' ;) I stumbled over another issue: feeding a tiny array ( `subvol.shape` is 4, 16, 8) with only a single foreground voxel (slipped through my filter) to leads to
```Python
0020-0864-0384
svm: 1 
Traceback (most recent call last):
  File "C:/Users/teforadmin/Anaconda3/envs/AY-312-DR-36/Scripts/analyseSubSkeletons.py", line 64, in <module>
    branch_data = summarize(Skeleton(subvol, spacing=1))
  File "C:\Users\teforadmin\Anaconda3\envs\AY-312-DR-36\lib\site-packages\skan\csr.py", line 326, in __init__
    _buffer_size_offset=_buffer_size_offset)
  File "C:\Users\teforadmin\Anaconda3\envs\AY-312-DR-36\lib\site-packages\skan\csr.py", line 249, in _build_skeleton_path_graph
    path_indptr[:m]), shape=(m-1, n))
  File "C:\Users\teforadmin\Anaconda3\envs\AY-312-DR-36\lib\site-packages\scipy\sparse\compressed.py", line 105, in __init__
    self.check_format(full_check=False)
  File "C:\Users\teforadmin\Anaconda3\envs\AY-312-DR-36\lib\site-packages\scipy\sparse\compressed.py", line 177, in check_format
    raise ValueError("Last value of index pointer should be less than "
ValueError: Last value of index pointer should be less than the size of index and data arrays
``` 
So I changed the input filter ( `np.amax(subvol > 0` (svm)) to a threshold ( `np.sum(subvol) >= thresh` (svs)) and set thresh to 10. However, ...
```Python
0032-0992-0464
svm: 1 svs: 41
Traceback (most recent call last):
  File "C:/Users/teforadmin/Anaconda3/envs/AY-312-DR-36/Scripts/analyseSubSkeletons.py", line 64, in <module>
    branch_data = summarize(Skeleton(subvol, spacing=1))
  File "C:\Users\teforadmin\Anaconda3\envs\AY-312-DR-36\lib\site-packages\skan\csr.py", line 326, in __init__
    _buffer_size_offset=_buffer_size_offset)
  File "C:\Users\teforadmin\Anaconda3\envs\AY-312-DR-36\lib\site-packages\skan\csr.py", line 244, in _build_skeleton_path_graph
    path_indices = np.zeros(n_points, dtype=int)
ValueError: negative dimensions are not allowed
```
41 voxels are 8% of this subvol (512 voxels). So I ramped up the threshold to 10%, however...
```Python
0032-0992-0472
svm: 1 svs: 60
Traceback (most recent call last):
  File "C:/Users/teforadmin/Anaconda3/envs/AY-312-DR-36/Scripts/analyseSubSkeletons.py", line 64, in <module>
    branch_data = summarize(Skeleton(subvol, spacing=1))
  File "C:\Users\teforadmin\Anaconda3\envs\AY-312-DR-36\lib\site-packages\skan\csr.py", line 316, in __init__
    spacing=spacing)
  File "C:\Users\teforadmin\Anaconda3\envs\AY-312-DR-36\lib\site-packages\skan\csr.py", line 624, in skeleton_to_csgraph
    graph = _pixel_graph(skelint, steps, distances, num_edges, height)
  File "C:\Users\teforadmin\Anaconda3\envs\AY-312-DR-36\lib\site-packages\skan\csr.py", line 59, in _pixel_graph
    graph = sparse.coo_matrix((data[:k], (row[:k], col[:k]))).tocsr()
  File "C:\Users\teforadmin\Anaconda3\envs\AY-312-DR-36\lib\site-packages\scipy\sparse\coo.py", line 146, in __init__
    raise ValueError('cannot infer dimensions from zero '
ValueError: cannot infer dimensions from zero sized index arrays
```
Thank you very much for your kind offer to help
I uploaded the training-skeleton and the python script to https://filesender.renater.fr/?s=download&token=b6c1bc7b-f787-49e7-9392-5a0e005bf00f 
The script is currently offset to start at 20, 864, 376, which is one iteration before the first occurance of the ValueError. 'div' is dividing the main-volume into div*div*div regular subvolumes. For data-wrangling I currently have it set to 100 which yields subvols of 4 16 8.

I did run this script through PyCharm's debugger a couple of times but to be honest, without really knowing, what I am looking for, the output - while impressive - didn't help me a lot. 

As for the motivation for the sub-volumes (yes, Skan can easily handle these 500MB), we want to measure the location-specific density of these skeletons (derived from blood vessel systems in the zebrafish optic tectum). As this is part of a high-throughput screen we decided for a regular grid instead of manually assigned ROIs. 
cheers, aRnim

**Comment by jni** [comment]
@ArnimJenett here is the data you are feeding my poor algorithm:

<img width="1200" alt="Screen Shot 2020-08-03 at 11 26 04 pm" src="https://user-images.githubusercontent.com/492549/89187554-ce5fd900-d5e0-11ea-8c53-f46d73ae9a18.png">

=P

You can use the following code to look at your data:

```python
import napari
from skimage import io

image = io.imread('skelonOC33_lee.C3.tif')
with napari.gui_qt():
    viewer = napari.view_image(image, contrast_limits=[0, 1])
```

It looks like the skeletonisation fails when there are "bubbles" in the binary objects. Calling `scipy.ndimage.binary_fill_holes` before skeletonization *should* fix the issue! (It fixes it for the small problematic subvolume.)

Now, in all honesty, the error message is *not* helpful and it should be fixed, but I don't know how I would properly detect this kind of issue. I'll leave the issue open until I have a better error message, but in the meantime I hope this fixes your issue!

**Comment by jni** [comment]
Oooh it's *super pretty* if you add `ndisplay=3` to that call. =D

<img width="1200" alt="Screen Shot 2020-08-03 at 11 39 14 pm" src="https://user-images.githubusercontent.com/492549/89188956-ad988300-d5e2-11ea-9fc8-0e44c3da6c87.png">

**Comment by jni** [comment]
@ArnimJenett can you confirm whether `binary_fill_holes` fixed your issue?

**Comment by ArnimJenett** [comment]
@jni, the `binary_fill_holes` gave us some trouble, not behaving as expected. In the end we settled on openCV's `floodfill`. 
Et voilà, now - on a clean skeleton - your Skan is performing perfectly, when we keep filtering against empty subvols. 
Thanks a lot for your help/advise.

**Comment by jarodhanko** [comment]
I was running into this same issue. Using binary_fill_holes mostly worked for me. However I did have one additional issue, which might be what ArnimJenett if referencing above.

`
import numpy as np
import skan

a = np.zeros((10,10))

skan.Skeleton(a) #fails

a[3][3]=1
skan.Skeleton(a) #fails

a[4][4]=1
skan.Skeleton(a) #fails

a[3][7]=1
skan.Skeleton(a) #fails

a[4][8]=1
skan.Skeleton(a) #success
`

Any time there is  a single pixel by itself, it fails. Any time there is only 2 pixels it fails. 

Simply checking that the skeleton has more than 2 pixels (after morphing to remove any single pixels), solves this problem. I am not sure why it breaks if there are only 2 pixels, but works fine if there are 2 separate groups of 2 pixels. In any case, I thought I would leave a comment here in case anyone else runs into the same issue.

**Comment by jni** [comment]
Thanks for writing in @jarodhanko! We should definitely fix skan so that those tiny skeletons (and even empty skeletons) work. Normally I'd say make a new issue but since this one is still open I'll just keep it open for reference. :smiley:
